### ISSUE TITLE
MATE 1.14.1 updates

### ISSUE THREAD

**Issue by geki-yaba** [oz123/mate-de-gentoo#18]
Some packages got a micro update. Simple bump does build here.
List of packages can be obtained here:

https://github.com/geki-yaba/mate-de-gentoo/commit/150678f88e43e04c0a4285a4ede2d6b9ddcb35bb

**Comment by oz123** [comment]
I merged your commit, can please config your git to include your email ?
This looks terrible---

```
 geki <root@localhost>
```
