### ISSUE TITLE
mate-base/mate: dependency of sys-apps/gnome-disk-utility

### ISSUE THREAD

**Issue by geki-yaba** [oz123/mate-de-gentoo#19]
Which feature does gnome-disk-utility bring I did miss before?
My desktop works just fine without. Therefore, I moved it into its on useflag: gnome.

Would it be ok to move it into another useflag than 'extra'?

**Comment by oz123** [comment]
I would like these ebuilds to stay as close as possible to gentoo's official ebuilds. I suggest you raise
such issues within the bugzillla of gentoo.

**Comment by geki-yaba** [comment]
Well, I better save that energy for something useful. ;-)
I know the answer. Both reasonings are understandable.
So I am not going to generate noise.
