### ISSUE TITLE
mate-extra/mate-netbook-1.14.0: actually make use of useflag: gtk3

### ISSUE THREAD

**Issue by geki-yaba** [oz123/mate-de-gentoo#20]
Diff can be seen here: https://github.com/geki-yaba/mate-de-gentoo/commit/22b0efbfcf8239a4910572b11852b11f311a02b4

**Comment by oz123** [comment]
@geki-yaba why no PR?

I really want to use your work, but why are you making it harder than necessary?

**Comment by oz123** [comment]
I merged your changes

**Comment by geki-yaba** [comment]
Is it possible to create a PR for a single commit? I just do not know.
I am used to work on 'diff -u' styled patches. That just works fine. ;-)
I know, git produces a proper timeline/log recording. O well ...

I will try with future 1.16 series.

**Comment by oz123** [comment]
Yes you can do a PR for a single commit ...
