### ISSUE TITLE
eom

### ISSUE THREAD

**Issue by gsra99** [oz123/mate-de-gentoo#26]
eom will build with dbus and gtk3 enabled, but fails to build with python and gtk3. Hence the ebuild line 26 should be changed from 

> gtk3? ( !dbus )"

to

> gtk3? ( !python )"

Please see [http://wiki.mate-desktop.org/status:gtk3](http://wiki.mate-desktop.org/status:gtk3) for more information.

**Comment by oz123** [comment]
This is already fixed in 1.16 and 1.14 ebuilds.
