### ISSUE TITLE
update to mate 1.16

### ISSUE THREAD

**Issue by gsra99** [oz123/mate-de-gentoo#27]
Mate desktop 1.16 was released on 21 September 2016. Will all ebuilds be updated to this version?

**Comment by oz123** [comment]
This repository will soon be merged with gentoo-mate. Mate 1.16 will be available in around one month.
You should not worry so much about it, since mate 1.16 is mostly GTK3 bug fixed, no new features.

**Comment by geki-yaba** [comment]
If you are brave you can have a look at MATE 1.16 from my forked repository here:

https://github.com/geki-yaba/mate-de-gentoo/tree/downstream (branch downstream for latest mate-themes fixes)

**Comment by oz123** [comment]
Ebuilds for mate 1.16 are now available. Have fun. Mate 1.16 is more gtk3 oriented, and I recommend building all the packages with gtk3
