### ISSUE TITLE
Version conflict in mate-1.14

### ISSUE THREAD

**Issue by NHOrus** [oz123/mate-de-gentoo#28]
mate-extra/mate-system-monitor-1.14.1 uses gtk_widget_class_set_css_name() from gtk+3.20
x11-themes/mate-themes-1.14.2 wants x11-libs/gtk+-3.18

**Comment by oz123** [comment]
Is this still relevant? Can you try the 1.16 ebuilds?

**Comment by NHOrus** [comment]
From your overlay or from the pull request in gentoo-mate? Trying from your overlay...

**Comment by oz123** [comment]
Both places have a good portion of same ebuilds.

**Comment by NHOrus** [comment]
Got from your port, appears to be working.

Should I post further issues here or in Gentoo bugzilla?

**Comment by oz123** [comment]
here please.
