### ISSUE TITLE
mate 1.16: upower does not suspend or hybernate

### ISSUE THREAD

**Issue by NHOrus** [oz123/mate-de-gentoo#30]
in kernel, CONFIG_HIBERNATION=y and CONFIG_SUSPEND=y
From pm-suspend and pm-hibernate operations complete successfully.
Options do not exist in menu poweroff button nor in mate-power-manager as possible targets for power events.

Global USE="X a52 aac acl acpi adns alsa amd64 archive bash-completion berkdb branding bzip2 cairo caps cdda cdr clang cli consolekit cracklib crypt cups cxx dbus dri dri3 dts dvd dvdr egl emboss encode exif fam ffmpeg firefox flac fortran gdbm gif glamor gles1 gles2 gnome-keyring gpm gtk hardened harfbuzz iconv icu idn ipv6 jpeg lcms libcxx libnotify libressl lzma mad mmx mmxext mng modules mp3 mp4 mpeg mtp multilib natspec ncurses networkmanager nls nptl offensive ogg opengl openmp pam pango pcre pdf png policykit ppds pulseaudio qt3support qt5 readline sdl seccomp session spell sse sse2 ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb vaapi vdpau vorbis wayland wxwidgets x264 xattr xcb xinerama xml xv xvid zlib zsh-completion"
Additional USE flags:
/etc/portage/package.use/all:sys-auth/consolekit pm-utils
/etc/portage/package.use/all:mate-extra/caja-extensions pidgin -cdr
/etc/portage/package.use/all:mate-base/mate-menus python

**Comment by oz123** [comment]
I encountered the same problem earlier today. I documented this here: https://wiki.gentoo.org/wiki/MATE
Make also sure you have all the latest packages from mate (1.16), update the rules in /etc/UPower too.

This solved the issue for me.

**Comment by NHOrus** [comment]
what about https://bugs.gentoo.org/show_bug.cgi?id=586302 ?

**Comment by oz123** [comment]
I am aware of that discussion, but the ebuilds here will mostly comply to what NP-Hardass would
prefer, such that they could be merged into Gentoo. 
Did you try to compile again and see if you get this to work?

**Comment by NHOrus** [comment]
Yes, your solution works.
