### ISSUE TITLE
mozo should depend on mate-menus[python]

### ISSUE THREAD

**Issue by NHOrus** [oz123/mate-de-gentoo#31]
If mate-menus compiled without USE=python, mozo fails with
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/mozo", line 22, in <module>
    from Mozo.MainWindow import MainWindow
  File "/usr/lib64/python2.7/site-packages/Mozo/MainWindow.py", line 19, in <module>
    import matemenu
ImportError: No module named matemenu
```
and silently if launched from mate-control-center  
Suggest explicit dependency in ebuild.

**Comment by NHOrus** [comment]
Alternatively, enable USE=python by default in mate-menu.

Or combine both.

**Comment by oz123** [comment]
@NHOrus thank you so much for all that feedback! I will try to fix this as soon as I can.

**Comment by NHOrus** [comment]
Oh, and this is valid for both 1.14 and 1.16

**Comment by oz123** [comment]
https://github.com/oz123/mate-de-gentoo/commit/a7b1063328bdb02141c449aeeddc80b63e3efb8d

Should fix this issue. Can you confirm this?

**Comment by NHOrus** [comment]
Yes, portage now gently asks that correct USE flag should be set
