### ISSUE TITLE
New mate 1.22.x release

### ISSUE THREAD

**Issue by joakim-tjernlund** [oz123/mate-de-gentoo#35]
Are you still maintaining this overlay?
If so, there is a new 1.22.x release of MATE

**Comment by oz123** [comment]
This new release is very well maintained in the main gentoo repository.

**Comment by oz123** [comment]
@joakim-tjernlund what's the urgence? Is there a bug that specifically hurts you?

**Comment by joakim-tjernlund** [comment]
We use MATE at work and there is always some problems with laptops and multiple monitors.
Hard to know what is causing these but hopefully there is some fixed by newer MATE.

**Comment by oz123** [comment]
Feel free to contact me on a private channel. I'm happy to help you with the upgrade.

**Comment by oz123** [comment]
@joakim-tjernlund ebuilds are all tested and published.

**Comment by joakim-tjernlund** [comment]
> @joakim-tjernlund ebuilds are all tested and published.

Thanks, will check it out soon

**Comment by oz123** [comment]
version 1.23 is also available.

**Comment by joakim-tjernlund** [comment]
Just added this overlay and had a quick look ...
One this I noted is that x11-libs/libXxf86misc has not been removed in your repo but
upstream has.

**Comment by oz123** [comment]
Can you please specify where is the reference for this?

**Comment by joakim-tjernlund** [comment]
Here is one:
https://git.mate-desktop.org/mate-control-center/commit/?h=1.22&id=989cb9ed3d29f78067a77cb6f67ee2385f2e9e3d

and there is a newer marco too in upstram

**Comment by joakim-tjernlund** [comment]
After this weekends updates in Gentoo I get a long delay when logging in(using sddm).
mate-session hangs for some 10-20 secs before continuing. Meanwhile I have a black screen.
Is it just me?

**Comment by mschemerii** [comment]
How did you update? I just did a new install last monday

**Comment by joakim-tjernlund** [comment]
I did an emerge -DNu world late this Sunday

**Comment by mschemerii** [comment]
I use lightDM and am noticing a delay that is longer than before. However, it is more like a 5 second delay, not truly significant on this VM with 1 CPU and 4096MB of RAM.

**Comment by joakim-tjernlund** [comment]
5 extra secs is a long time, there is something holding up mate-session that
stems form this weekends update but I have no idea what caused it.

BTW, libXxf86misc is removed for mate-control-center and mate-settings-daemon too
Nothing in MATE should depend on that pkg anymore.

**Comment by oz123** [comment]
libXxf86misc is already removed from the ebuilds.

**Comment by joakim-tjernlund** [comment]
grep libXxf86mis . -r
./mate-base/mate-control-center/mate-control-center-1.20.4.ebuild:	x11-libs/libXxf86misc:0
./mate-base/mate-control-center/mate-control-center-1.22.1.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-control-center/mate-control-center-1.22.2.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-control-center/mate-control-center-1.23.2.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-control-center/mate-control-center-9999.ebuild:	x11-libs/libXxf86misc:0
./mate-base/mate-settings-daemon/mate-settings-daemon-1.20.3-r1.ebuild:	x11-libs/libXxf86misc:0
./mate-base/mate-settings-daemon/mate-settings-daemon-1.22.0-r1.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-settings-daemon/mate-settings-daemon-1.22.1.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-settings-daemon/mate-settings-daemon-1.23.2.ebuild:	x11-libs/libXxf86misc
./mate-base/mate-settings-daemon/mate-settings-daemon-9999.ebuild:	x11-libs/libXxf86misc:0
./mate-extra/mate-screensaver/mate-screensaver-1.22.1.ebuild:	x11-libs/libXxf86misc
./mate-extra/mate-screensaver/mate-screensaver-1.22.2.ebuild:	x11-libs/libXxf86misc
./mate-extra/mate-screensaver/mate-screensaver-1.23.1.ebuild:	x11-libs/libXxf86misc

Seem to be some left

**Comment by oz123** [comment]
I only removed it from newer versions not from older versions where it is still necessary.
I still haven't push the changes for the two other ebuilds. This should not be the cause for the issue you are experiencing. 
Please open a new issue to track the removal of libXxf86misc.

**Comment by joakim-tjernlund** [comment]
I think it is optional in all MATE pkgs, just that Gentoo made it mandatory

Anyhow, I found the pkg causing the delay, it is gnome-base/gnome-keyring 2.28.2 went to 3.31.91-r1.
Looking into https://git.mate-desktop.org/mate-session-manager/log/
there are "Remove GNOME_KEYRING_LIFETIME_FD" and "Fix timeout with gnome-keyring 3.34"
Maybe that 3.34 is really 3.31 ?

**Comment by joakim-tjernlund** [comment]
Yes, adding those two patches to  mate-base/mate-session-manager-1.22.2 made the delay go away :)

**Comment by joakim-tjernlund** [comment]
https://github.com/mate-desktop/mate-session-manager/issues/226

**Comment by oz123** [comment]
> Yes, adding those two patches to mate-base/mate-session-manager-1.22.2 made the delay go away :)

Which patches exactly? Can you be more specific. I think it will help your issue reported upstream too.

**Comment by joakim-tjernlund** [comment]
https://git.mate-desktop.org/mate-session-manager/commit/?h=1.22&id=ee8fd9ad5de6b2c2ae8f05aaf0c6fd130ce8906f

https://git.mate-desktop.org/mate-session-manager/commit/?h=1.22&id=3ecc4bf1b660dfff5e7b7a69f38d80a5d579918a

**Comment by oz123** [comment]
@joakim-tjernlund FYI I removed libXxf86misc in the latest versions of the  ebuilds where it was appropriate.
