### ISSUE TITLE
mate-session-manager

### ISSUE THREAD

**Issue by mschemerii** [oz123/mate-de-gentoo#36]
The ebuild for mate-desktop does not have mate-session-manager. Without this, the MATE session does not appear in lightDM as a selectable option.

**Comment by oz123** [comment]
This is included in the ebuild `mate-base/mate`
https://github.com/oz123/mate-de-gentoo/blob/master/mate-base/mate/mate-1.23.ebuild

I didn't choose to name it so confusingly. These ebuilds are keeping the naming convention of the main Gentoo repository.

**Comment by mschemerii** [comment]
So, is the proper install to:
emerge mate
?

**Comment by oz123** [comment]
Yes, just do:

```
emerge -a mate-base/mate
```

Depending on which use flags you set , different packages are installed.
See https://wiki.gentoo.org/wiki/MATE#USE_flags
