### ISSUE TITLE
mate-base/mate-applets should depend on sys-power/cpupower-5.4

### ISSUE THREAD

**Issue by corvus1** [oz123/mate-de-gentoo#39]
mate-base/mate-applets should depend on sys-power/cpupower-5.4 as it doesn't build with 4.13.0

**Comment by oz123** [comment]
Can you post the build error? 
Which ebuild version fails? 1.22 or 1.23?

I can't confirm this behavior. Both ebuild version built successfully on my machine.

```
$ equery u cpupower
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-power/cpupower-4.13.0:
 U I
 + + nls : Add Native Language Support (using gettext - GNU locale utilities)
$ equery u mate-applets
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for mate-base/mate-applets-1.22.0:
 U I
 + + X         : Add support for X11
 + + ipv6      : Add support for IP version 6
 + + policykit : Enable PolicyKit authentication support
 + + upower    : Enable power management support
oznn@oz-nn:~/Software/mate-de-gentoo [±|master ✓|] $ equery u mate-applets
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]

$ sudo emerge -a =mate-base/mate-applets-1.23.0

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] mate-base/mate-applets-1.23.0 [1.22.2]

!!! The following installed packages are masked:
- dev-util/idea-community-2019.1.191.6183.87::gentoo (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
# Michał Górny <mgorny@gentoo.org> (2019-12-01)
# Unresolved license issues.  No reply from maintainer.
# Removal in 30 days.  Bug #694262.

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.


Would you like to merge these packages? [Yes/No] yes

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) mate-base/mate-applets-1.23.0::mate-de-gentoo
 * mate-applets-1.23.0.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                                                                             [ ok ]
>>> Unpacking source...
>>> Unpacking mate-applets-1.23.0.tar.xz to /var/tmp/portage/mate-base/mate-applets-1.23.0/work
>>> Source unpacked in /var/tmp/portage/mate-base/mate-applets-1.23.0/work
>>> Preparing source in /var/tmp/portage/mate-base/mate-applets-1.23.0
....
....
 * Final size of build directory: 112212 KiB (109.5 MiB)
 * Final size of installed tree:   82000 KiB ( 80.0 MiB)

strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/libexec/mate-applets/mate-charpick-applet
   /usr/libexec/mate-applets/mate-drivemount-applet
   /usr/libexec/mate-applets/mate-geyes-applet
   /usr/libexec/mate-applets/stickynotes-applet
   /usr/libexec/mate-applets/trashapplet
   /usr/libexec/mate-applets/command-applet
   /usr/libexec/mate-applets/mate-multiload-applet
   /usr/libexec/mate-applets/mate-netspeed-applet
   /usr/libexec/mate-applets/battstat-applet
   /usr/libexec/mate-applets/mateweather-applet
   /usr/libexec/mate-applets/accessx-status-applet
   /usr/libexec/mate-applets/mate-cpufreq-applet
   /usr/libexec/mate-applets/timer-applet
   /usr/bin/mate-cpufreq-selector

>>> Installing (1 of 1) mate-base/mate-applets-1.23.0::mate-de-gentoo
 * Updating icons cache ...                                                                                                                                                                                                           [ ok ]
 * Updating GSettings schemas ...                                                                                                                                                                                                     [ ok ]
 * Updating icons cache ...                                                                                                                                                                                                           [ ok ]
 * Updating GSettings schemas ...                                                                                                                                                                                                     [ ok ]

>>> Recording mate-base/mate-applets in "world" favorites file...
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
$ date
Sun 08 Dec 2019 07:53:55 AM CET
$ equery u mate-applets
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for mate-base/mate-applets-1.23.0:
 U I
 + + X         : Add support for X11
 + + ipv6      : Add support for IP version 6
 + + policykit : Enable PolicyKit authentication support
 + + upower    : Enable power management support

**Comment by corvus1** [comment]
[build.log](https://github.com/oz123/mate-de-gentoo/files/3935957/build.log)

See build log mate-base/mate-applets-1.23.0 with sys-power/cpupower-4.13.0 installed.

quote:
```

cpufreq-selector-libcpufreq.c:96:38: error: dereferencing pointer to incomplete type ‘CPUFreqFrequencyList’ {aka ‘struct cpufreq_frequencies’}
   96 |  for (freq = freqs; freq; freq = freq->next) {


```
```
* Found these USE flags for mate-base/mate-applets-1.23.0:
 U I
 + + X         : Add support for X11
 + + ipv6      : Add support for IP version 6
 + + policykit : Enable PolicyKit authentication support
 + + upower    : Enable power management support

```

**Comment by oz123** [comment]
Can you specify which kernel version you have? Maybe this is related?
I'm using kernel 4.19.88 currently.

**Comment by corvus1** [comment]
> Can you specify which kernel version you have? Maybe this is related?
> I'm using kernel 4.19.88 currently.

Sure.

` uname -a
Linux ione64 5.4.0-gentoo #2 SMP PREEMPT Tue Nov 26 15:15:06 +04 2019 x86_64 Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz GenuineIntel GNU/Linux
`

**Comment by oz123** [comment]
I am not sure where to look further, but I am also not sure your requirements suggestion is correct.
I don't see it any other distribution, and I don't see it `configure.ac`.

Last question: which gcc are you using?

```
# gcc --version
gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by corvus1** [comment]
> I am not sure where to look further, but I am also not sure your requirements suggestion is correct.
> I don't see it any other distribution, and I don't see it `configure.ac`.
> 
> Last question: which gcc are you using?
> 
> ```
> # gcc --version
> gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

I'm not particularly sure myself now. But I was able to reproduce the problem quite reliably.
```
gcc --version
gcc (Gentoo 9.2.0-r2 p3) 9.2.0

```

**Comment by oz123** [comment]
Can you report the issue in mate-applets upstream ? Let's see what they say. Maybe the upstream developers know better (for sure they know better than me!)

**Comment by corvus1** [comment]
> Can you report the issue in mate-applets upstream ? Let's see what they say. Maybe the upstream developers know better (for sure they know better than me!)

I'm sorry to say, but I'm a bit too lazy to do that. The issue seems minor, and easily resolved by just upgrading sys-power/cpupower so...

**Comment by oz123** [comment]
By the way:
Debian testing has  libcpupower-dev (5.3.9-3) currently   
https://packages.debian.org/bullseye/libcpupower-dev
And the tests are running again this version ...

See here: https://github.com/mate-desktop/mate-applets/blob/cec742f132e318db1de4d01d841fea15238798c3/.travis.yml#L57

So maybe you are right. Which brings the question of how come it builds on my system?
Maybe my interpretation is wrong?

**Comment by corvus1** [comment]
https://github.com/mate-desktop/mate-applets/issues/394
here's something perhaps related.

**Comment by corvus1** [comment]
I skimmed over it, and it seems like it works for you because you have older kernel.

**Comment by oz123** [comment]
Seems it's after all a kernel related issue. Because we have different kernels.
You were quicker. 
Ok. Do you have a 4.19.X kernel lying around which you can test?

**Comment by corvus1** [comment]
I'll try installing the older kernel sources but I'm not sure it guarantees mate-applets will build against it. 
However, I suspect ultimately to fix this issue you have to pull this https://github.com/mate-desktop/mate-applets/pull/397/commits/742651b7fa72c91215584647eb82e58862830365 patch from upstream.

**Comment by oz123** [comment]
That is no problem to add. But I can't test it. So you can simply add the patch to files/
and activate the patch by modifying the ebuild. 
I would be happy to merge a PR for that.

**Comment by corvus1** [comment]
You'll be happy to know that I was able to build mate-applets with cpupower-4.13 when I downgraded sys-kernel/linux-headers to 4.19. Previously I had version 5.3-r1 installed.

**Comment by oz123** [comment]
~~I could not cleanly apply the patch from upstream. This requires a bit manual work, which I can dedicate time too now. If this is really important you, can you please create a patch and send a PR?~~
This patch is already in 1.23 release...

**Comment by corvus1** [comment]
Like I said. It's not _that_ important to me.

**Comment by oz123** [comment]
OK. I am closing this issue. Thanks for reporting anyway. Feel free to open other issues and give feedback .

**Comment by corvus1** [comment]
> This patch is already in 1.23 release...

Now that's weird. If it's in 1.23, it should build against both old and new kernel headers no problem. Perhaps the patch doesn't quite solve the problem it's aimed to solve.

**Comment by oz123** [comment]
I guess you are right. Maybe an issue upstream is the right thing here. 
I will update my kernel maybe in a month or so, so I can test it then.

**Comment by corvus1** [comment]
Or maybe it's some kind of compatibility issue between cpupower and linux-headers. 
It seems like I've discovered some obscure corner case by mixing amd64 and ~amd64 branches. It wouldn't be the first, to be honest.
