### ISSUE TITLE
app-text/atril should depend on app-text/texlive-core

### ISSUE THREAD

**Issue by corvus1** [oz123/mate-de-gentoo#40]
Since that https://github.com/mate-desktop/atril/issues/186#issuecomment-566439530 bundled synctex is dropped from atril and now it relies on distro provided synctex, which in Gentoo is provided by app-text/texlive-core.

**Comment by oz123** [comment]
Hi, thank you for reporting the issue.  I believe that  adding this as a mandatory dependency  is not desired.  I would add  cen optional dependency  with a USE flag. WDYT?

**Comment by corvus1** [comment]
> Hi, thank you for reporting the issue. I believe that adding this as a mandatory dependency is not desired. I would add cen optional dependency with a USE flag. WDYT?

I'd love it to be optional so I don't have to install the whole tex-mess. But as it is, the latest atril fails at configure stage without texlive-core.

**Comment by oz123** [comment]
I have started working on a patch, see https://github.com/mate-desktop/atril/pull/436

**Comment by oz123** [comment]
@corvus1 btw, I could not compile this package with glib from the getoo repos. Did you bump your glib to 2.62?

**Comment by corvus1** [comment]
No, I didn't. Compiled fine for me as soon as I installed texlive-core.

**Comment by oz123** [comment]
Like I mentioned earlier, I started working on a set of patches to make synctex an optional feature.
I would be thankful if you can test it. Currently, the branch does not even compile, since it's WIP.

**Comment by corvus1** [comment]
Sure, I'll do what I can.

**Comment by oz123** [comment]
fixed in https://github.com/oz123/mate-de-gentoo/commit/25f6f41390c2aaf4d6c4c73766a267169f3c178e

**Comment by corvus1** [comment]
Your patch seems to work fine for me. It builds and works.

**Comment by oz123** [comment]
Can you also please confirm that on the upstream PR?

**Comment by corvus1** [comment]
I'm not sure I should, because I tested your patch from the overlay, not the actual code from git. But I did it anyway. :-)

**Comment by oz123** [comment]
The patches are in sync. Thanks!
