### ISSUE TITLE
Consider adding this to code.funtoo.org (Funtoo)

### ISSUE THREAD

**Issue by ghost** [oz123/mate-de-gentoo#43]
Your ebuilds would be much appreciated if they were in Funtoo Linux :) as submitting is as easy as opening a PR. Please consider adding this to Funtoo Linux :heart:

**Comment by oz123** [comment]
@VentGrey I appreciate the feedback. Two problems:
1. I  have to create an Atlassian (easy to solve though)
2. I don't have a clue which kit the ebuilds go too. 

Care to comment?

**Comment by ghost** [comment]
* You have to create your account [here](https://auth.funtoo.org/login)
* For kits your ebuilds can go in the [Kit fixups kit](https://code.funtoo.org/bitbucket/projects/CORE/repos/kit-fixups/browse)

About some concerns you mentioned in your readme:

* Funtoo doesn't use systemd so, your ebuilds are great!
* The not officially MATE packages can go [here](https://code.funtoo.org/bitbucket/projects/CO/repos/flora/browse) in the flora kit :)

We really hope to see your ebuilds around here :)

**Comment by oz123** [comment]
So you want me to find out each ebuild in those kits and submit a PR?

I see that  mozo is in:

https://code.funtoo.org/bitbucket/projects/CORE/repos/kit-fixups/browse/desktop-kit/curated/x11-misc/mozo

This is no trivial job to find where each ebuild goes. I guess this really works for funtoo users, but this seems like a lot of extra work for me. I am sorry, but I am going to pass on this request unless you will be more specific how this works.
