### ISSUE TITLE
app-text/atril-1.24.0 should depend on >dev-libs/glib-2.62.0

### ISSUE THREAD

**Issue by nuts424** [oz123/mate-de-gentoo#45]
emerge atril-1.24.0 fails at checking glib version due to missing dependency in atril-1.24 ebuild

`
checking for gtk+-3.0 >= 3.22.0 gio-2.0 >= 2.62.0... no
configure: error: Package requirements (gtk+-3.0 >= 3.22.0 gio-2.0 >= 2.62.0) were not met:

Requested 'gio-2.0 >= 2.62.0' but version of GIO is 2.60.7
`

**Comment by oz123** [comment]
That is correct. Thanks.
