### ISSUE TITLE
Section 'mate-de-gentoo' in repos.conf has name different from repository name 'gentoo-mate' set inside repository

### ISSUE THREAD

**Issue by corvus1** [oz123/mate-de-gentoo#55]
I get that message when syncing, maybe it's something that should be taken a look at.
I suspect it's referring to 
https://github.com/oz123/mate-de-gentoo/blob/1e56d12b97fbd447cd64649b53f134a3cc56f8d0/layman.xml#L4

**Comment by oz123** [comment]
Should be fine now. Please reopen if this is still broken.

**Comment by corvus1** [comment]
It's working fine now, thanks. On the other note, that seems backwards: 
https://github.com/oz123/mate-de-gentoo/blob/32b99fabac0819787c165e3947f1cb13bd14d367/layman.xml#L8-L9

**Comment by oz123** [comment]
Happens, sleepless night. Will fix it.
