### ISSUE TITLE
Evaluate dependency to dev-libs/dbus-glib

### ISSUE THREAD

**Issue by ghost** [oz123/mate-de-gentoo#59]
Some MATE ebuilds still depend on obsolete dev-libs/dbus-glib, however since MATE 1.22 the code was migrated to GDbus (i.e. depend on dev-libs/glib only)

MATE packages are the last ones depending on dbus-glib on my system, would be nice to evaluate if this dep is still required, so we can finally get rid of it.

**Comment by oz123** [comment]
Sure thing! Can you help too? I am really looking for a helping hand here.

**Comment by ghost** [comment]
Hello,
I had a look on my side, actually MATE only partially migrated to GDbus, so we still need dbus-glib for some packages.

The only package which was cleaned-up is mate-panel (>= 1.24) ; we can remove the dev-libs/dbus-glib dependency from the ebuilds.
For the rest, we have to wait for migration from upstream...

**Comment by oz123** [comment]
Can you please submit a PR?

**Comment by ghost** [comment]
PR #70 created :-)
