### ISSUE TITLE
mate-base/mate still need mate-1.24 version in deps

### ISSUE THREAD

**Issue by Cerberios** [oz123/mate-de-gentoo#69]
Hello there!

Please, can You check is dependencies OK? I guess .ebuild file for mate-base/mate not updated.
Thanks!

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

mate-base/mate-desktop:0

  (mate-base/mate-desktop-1.26.0:0/0::mate-de-gentoo, ebuild scheduled for merge) USE="X introspection startup-notification -debug" ABI_X86="(64)" conflicts with
    =mate-base/mate-desktop-1.24* required by (mate-base/mate-1.24:0/0::mate-de-gentoo, installed) USE="base notification -bluetooth -extras -help -themes" ABI_X86="(64)"
    ^                       ^^^^^

mate-base/mate-session-manager:0

  (mate-base/mate-session-manager-1.26.0-r1:0/0::mate-de-gentoo, ebuild scheduled for merge) USE="elogind ipv6 nls xtrans -debug -gles2 -gnome-keyring -systemd" ABI_X86="(64)" conflicts with
    =mate-base/mate-session-manager-1.24* required by (mate-base/mate-1.24:0/0::mate-de-gentoo, installed) USE="base notification -bluetooth -extras -help -themes" ABI_X86="(64)"
    ^                               ^^^^^

**Comment by oz123** [comment]
Can you please post the exact command you used and also any relevant package accept keyword files?
Thanks.

**Comment by Cerberios** [comment]
Hello, sure - please:

GentooMateEnv ~ #vim /etc/portage/package.accept_keywords/custom
mate-extra/* ~amd64
mate-base/* ~amd64
--------------------------------
Command for update:
GentooMateEnv ~ # emerge -av --deep --update --with-bdeps=y --backtrack=100 mate-base/mate

**Comment by oz123** [comment]
Unmasking so many versions at once with `*` might be the cause.
Please try again with:

```
>=mate-extra/*-1.26 ~amd64
>=mate-base/*-1.26 ~amd64
```
