### ISSUE TITLE
gtk3 tweaks to compile

### ISSUE THREAD

**Issue by geki-yaba** [oz123/mate-de-gentoo#7]
following diff shows what to update, mostly "typos".

mate-extra/mate-media: upstream removed gstreamer code; compiles without gstreamer-0.10. though, I guess it needs it at runtime?!

media-gfx/eom has a linker error I quite do not get: cairo is missing a DSO symbol in libX11.

[mate.diff.txt](https://github.com/oz123/gentoo-mate-112/files/67941/mate.diff.txt)

**Comment by geki-yaba** [comment]
media-libs/eom compile fix: change linker command manually(see below), then ebuild ... compile/install/qmerge

old: '... .libs/libtotemscrsaver.a ../jpegutils/.libs/libeom-jpegutils.a ...'
new: '... .libs/libtotemscrsaver.a -lX11 ../jpegutils/.libs/libeom-jpegutils.a ...'

**Comment by oz123** [comment]
@geki-yaba , I appreciate the edffort. Can you please make a pull request? It makes the review job way easier. 

Thank you.

**Comment by geki-yaba** [comment]
thanks for merging. closing ...
