### ISSUE TITLE
libmatemixer has wrong PA dep

### ISSUE THREAD

**Issue by joakim-tjernlund** [oz123/mate-de-gentoo#71]
Should be pulseaudio? ( >=media-sound/pulseaudio-5.0.0:0[glib]
see https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=17f25103fc9072646cd51489544a341ec3324690

**Comment by oz123** [comment]
Cool, thanks for letting me know. I will create a patch here too.

**Comment by joakim-tjernlund** [comment]
no need for a patch just remove alsa part from the depend in the ebuild.
It prevent merging pulseaudio 15.99.1

**Comment by joakim-tjernlund** [comment]
A general note: I think this is ready for Gentoo proper now.

**Comment by oz123** [comment]
I am working on upstreaming the ebuilds. By patch, I meant a new commit. Not a patch for the source code. Sorry for the misunderstanding.

**Comment by joakim-tjernlund** [comment]
ping
