### ISSUE TITLE
mate-base/mate still depends on last-rited x11-themes/mate-themes-meta

### ISSUE THREAD

**Issue by corvus1** [oz123/mate-de-gentoo#74]
https://github.com/oz123/mate-de-gentoo/blob/30460416545f866f389d6b905b8db18e2a246caf/mate-base/mate/mate-1.26.0.ebuild#L46

**Comment by oz123** [comment]
Fixed in mate-1.26.0-r1.ebuild

**Comment by corvus1** [comment]
If you develop in the overlay, and then do PRs to ::gentoo, you'll have the classic problem of syncing the changes. Just to give you a heads-up https://bugs.gentoo.org/799668#c2 comments 2-4. 

I'm not criticising your workflow, but it is something to think about. There are ways to sync the changes with the overlay. KDE project does it, I think they have some scripts and such. But it needs to be deliberately addressed, with 40-something packages in MATE, you will start losing changes. 

I know, because I started doing the same about a week ago. And there are 3 packages in my overlay. And it's already staring me in the face. :-) I can already tell where this is going.

**Comment by oz123** [comment]
The long term plan is to deprecate this repo. I already did most of the upstreaming.
